import type {
  DriverGrowthProfile,
  GrowthExperiment,
  MarketplaceLoad,
  MarketplaceSignal,
} from "./types";

export const defaultDriverGrowthProfile: DriverGrowthProfile = {
  id: "driver-001",
  name: "Owner Operator A",
  homeBase: "Phoenix, AZ",
  truckType: "Dry Van",
  hoursRemaining: 8.5,
  maxDeadheadMiles: 75,
  minRatePerMile: 2.1,
  preferredTripLength: "medium",
  preferredRegions: ["Southwest", "Mountain West"],
  fuelSensitivity: "high",
  parkingRiskTolerance: "medium",
};

export const marketplaceLoads: MarketplaceLoad[] = [
  {
    id: "load-001",
    pickupCity: "Phoenix",
    pickupState: "AZ",
    dropoffCity: "Denver",
    dropoffState: "CO",
    payout: 2150,
    miles: 830,
    deadheadMiles: 42,
    estimatedFuelCost: 410,
    pickupWindow: "Today 4:00 PM",
    dropoffWindow: "Tomorrow 7:00 PM",
    parkingRisk: "low",
    hosFeasible: true,
    brokerReliability: 92,
    returnLoadProbability: 78,
    documentRisk: "low",
    routeRisk: "medium",
    equipment: "Dry Van",
  },
  {
    id: "load-002",
    pickupCity: "Tucson",
    pickupState: "AZ",
    dropoffCity: "Salt Lake City",
    dropoffState: "UT",
    payout: 1880,
    miles: 720,
    deadheadMiles: 108,
    estimatedFuelCost: 365,
    pickupWindow: "Today 7:00 PM",
    dropoffWindow: "Tomorrow 8:30 PM",
    parkingRisk: "medium",
    hosFeasible: true,
    brokerReliability: 81,
    returnLoadProbability: 70,
    documentRisk: "medium",
    routeRisk: "medium",
    equipment: "Dry Van",
  },
  {
    id: "load-003",
    pickupCity: "Las Vegas",
    pickupState: "NV",
    dropoffCity: "Reno",
    dropoffState: "NV",
    payout: 1220,
    miles: 438,
    deadheadMiles: 305,
    estimatedFuelCost: 235,
    pickupWindow: "Tomorrow 6:30 AM",
    dropoffWindow: "Tomorrow 5:00 PM",
    parkingRisk: "high",
    hosFeasible: false,
    brokerReliability: 68,
    returnLoadProbability: 48,
    documentRisk: "medium",
    routeRisk: "high",
    equipment: "Dry Van",
  },
  {
    id: "load-004",
    pickupCity: "Albuquerque",
    pickupState: "NM",
    dropoffCity: "Dallas",
    dropoffState: "TX",
    payout: 1760,
    miles: 645,
    deadheadMiles: 62,
    estimatedFuelCost: 330,
    pickupWindow: "Tomorrow 9:00 AM",
    dropoffWindow: "Fri 2:00 PM",
    parkingRisk: "medium",
    hosFeasible: true,
    brokerReliability: 88,
    returnLoadProbability: 82,
    documentRisk: "low",
    routeRisk: "low",
    equipment: "Dry Van",
  },
  {
    id: "load-005",
    pickupCity: "Phoenix",
    pickupState: "AZ",
    dropoffCity: "Los Angeles",
    dropoffState: "CA",
    payout: 1325,
    miles: 372,
    deadheadMiles: 18,
    estimatedFuelCost: 230,
    pickupWindow: "Today 3:00 PM",
    dropoffWindow: "Tomorrow 9:00 AM",
    parkingRisk: "high",
    hosFeasible: true,
    brokerReliability: 74,
    returnLoadProbability: 91,
    documentRisk: "high",
    routeRisk: "medium",
    equipment: "Dry Van",
  },
  {
    id: "load-006",
    pickupCity: "Flagstaff",
    pickupState: "AZ",
    dropoffCity: "Boise",
    dropoffState: "ID",
    payout: 2380,
    miles: 895,
    deadheadMiles: 138,
    estimatedFuelCost: 480,
    pickupWindow: "Fri 8:00 AM",
    dropoffWindow: "Sat 8:00 PM",
    parkingRisk: "low",
    hosFeasible: true,
    brokerReliability: 95,
    returnLoadProbability: 61,
    documentRisk: "low",
    routeRisk: "medium",
    equipment: "Flatbed",
  },
  {
    id: "load-007",
    pickupCity: "Yuma",
    pickupState: "AZ",
    dropoffCity: "San Diego",
    dropoffState: "CA",
    payout: 980,
    miles: 188,
    deadheadMiles: 56,
    estimatedFuelCost: 110,
    pickupWindow: "Today 5:30 PM",
    dropoffWindow: "Tomorrow 6:00 AM",
    parkingRisk: "medium",
    hosFeasible: true,
    brokerReliability: 86,
    returnLoadProbability: 89,
    documentRisk: "medium",
    routeRisk: "low",
    equipment: "Reefer",
  },
  {
    id: "load-008",
    pickupCity: "Mesa",
    pickupState: "AZ",
    dropoffCity: "Kansas City",
    dropoffState: "MO",
    payout: 2650,
    miles: 1175,
    deadheadMiles: 26,
    estimatedFuelCost: 590,
    pickupWindow: "Tomorrow 1:00 PM",
    dropoffWindow: "Sun 11:00 AM",
    parkingRisk: "low",
    hosFeasible: true,
    brokerReliability: 90,
    returnLoadProbability: 67,
    documentRisk: "low",
    routeRisk: "low",
    equipment: "Dry Van",
  },
];

export const driverFeedback = [
  "I keep clicking loads that look good but the deadhead kills the profit.",
  "I wish I knew parking risk before accepting a late-night delivery.",
  "Fuel prices change whether a load is actually worth it.",
  "I do not trust a load unless I understand the pickup and dropoff timing.",
  "Sometimes the best paying load is not the best load after HOS.",
  "I want to know whether I can find another load near the dropoff.",
  "Too much time is spent comparing loads across different signals.",
  "I would book faster if the app showed net payout instead of only gross payout.",
];

export const growthKpis = [
  {
    label: "Onboarding completion",
    value: "72%",
    explanation: "Drivers who finish preference capture before first search.",
    trend: "+9 pts",
  },
  {
    label: "Recommendation CTR",
    value: "38%",
    explanation: "AI-ranked loads opened from the recommendation stack.",
    trend: "+12%",
  },
  {
    label: "Booking request rate",
    value: "21%",
    explanation: "Saved loads that become a booking request.",
    trend: "+6%",
  },
  {
    label: "7-day retention",
    value: "52%",
    explanation: "Drivers returning for another marketplace session.",
    trend: "+5 pts",
  },
];

export const marketplaceSignals: MarketplaceSignal[] = [
  {
    id: "signal-load-board",
    name: "Load board inventory",
    category: "load_board",
    status: "connected",
    freshness: "Updated 2 min ago",
    confidence: 94,
    impact: "Keeps discovery inventory broad enough for personalized ranking.",
  },
  {
    id: "signal-fuel",
    name: "Fuel price partner",
    category: "fuel",
    status: "mocked",
    freshness: "Seeded demo estimate",
    confidence: 72,
    impact: "Turns gross payout into a net-profit estimate on every load.",
  },
  {
    id: "signal-parking",
    name: "Parking availability",
    category: "parking",
    status: "mocked",
    freshness: "Seeded risk tier",
    confidence: 68,
    impact: "Surfaces late-night delivery risk before booking.",
  },
  {
    id: "signal-routing",
    name: "Truck-safe routing",
    category: "routing",
    status: "connected",
    freshness: "Demo route constraints",
    confidence: 88,
    impact: "Penalizes routes with operational friction or constrained corridors.",
  },
  {
    id: "signal-broker",
    name: "Broker reliability",
    category: "broker",
    status: "mocked",
    freshness: "30-day score window",
    confidence: 75,
    impact: "Improves trust by reducing slow-pay and cancellation risk.",
  },
  {
    id: "signal-docs",
    name: "Document OCR",
    category: "documents",
    status: "mocked",
    freshness: "Seeded friction flags",
    confidence: 70,
    impact: "Flags billing/document friction before the driver commits.",
  },
  {
    id: "signal-hos",
    name: "HOS/ELD signal",
    category: "hos",
    status: "mocked",
    freshness: "Driver profile snapshot",
    confidence: 73,
    impact: "Prevents recommendations that are not feasible under remaining hours.",
  },
];

export const growthExperiments: GrowthExperiment[] = [
  {
    id: "exp-net-profit",
    title: "Net Profit on Load Cards",
    hypothesis: "Net estimate improves booking request conversion.",
    audience: "New owner-operators in first 7 days",
    treatment: "Show estimated net profit above gross payout on cards.",
    primaryMetric: "Booking request rate",
    target: "+10% relative lift",
    risk: "Drivers may challenge estimates if inputs are unclear.",
    effort: "M",
    status: "queued",
  },
  {
    id: "exp-parking-risk",
    title: "Parking Risk Badge",
    hypothesis: "Showing parking risk increases trust and reduces abandoned route planning.",
    audience: "Loads with delivery windows after 6 PM",
    treatment: "Add low/medium/high parking badge to the discovery stack.",
    primaryMetric: "Load detail to save rate",
    target: "+8% relative lift",
    risk: "Risk copy must not overstate confidence.",
    effort: "S",
    status: "designing",
  },
  {
    id: "exp-return-load",
    title: "Return Load Probability",
    hypothesis: "Showing return-load probability improves confidence on long-haul loads.",
    audience: "Drivers considering trips above 700 miles",
    treatment: "Show a return-load confidence pill with lane context.",
    primaryMetric: "Long-haul booking request rate",
    target: "+6% relative lift",
    risk: "Partner inventory freshness must stay transparent.",
    effort: "M",
    status: "queued",
  },
  {
    id: "exp-ai-explanation",
    title: "AI Explanation Card",
    hypothesis: "Explainability improves trust in recommendations.",
    audience: "Drivers who open at least two load details",
    treatment: "Add concise why-this-load reasoning with risks included.",
    primaryMetric: "Recommendation CTR",
    target: "+12% relative lift",
    risk: "Generated text must preserve deterministic scoring facts.",
    effort: "M",
    status: "running",
  },
  {
    id: "exp-onboarding",
    title: "Onboarding Preference Capture",
    hypothesis: "More personalized onboarding improves first-load save rate.",
    audience: "New marketplace drivers",
    treatment: "Capture HOS, deadhead, region, fuel, and parking preferences early.",
    primaryMetric: "First-load save rate",
    target: "+15% relative lift",
    risk: "Too many fields can reduce onboarding completion.",
    effort: "L",
    status: "queued",
  },
];

export const bookingFunnel = [
  { stage: "Onboarding started", count: 1200 },
  { stage: "Onboarding completed", count: 864 },
  { stage: "First load viewed", count: 732 },
  { stage: "Load saved", count: 456 },
  { stage: "Booking requested", count: 252 },
  { stage: "Booking confirmed", count: 108 },
];
