import type { Partner, PartnershipTerms, Payout, Referral } from "./types";

export const acmePartner: Partner = {
  id: "partner_acme",
  legalName: "Acme Fuel Solutions LLC",
  displayName: "Acme Fuel Solutions",
  type: "Fuel card reseller",
  tier: "Silver",
  ownerName: "Mihir",
  primaryContactName: "Sarah Mendez",
  primaryContactEmail: "sarah@acmefuel.example",
  signingAuthorityName: "Marcus Reyes",
  signingAuthorityEmail: "marcus@acmefuel.example",
  lifecycleStage: "active",
};

export const acmeTerms: PartnershipTerms = {
  partnerTier: "Silver",
  revenueSharePct: 15,
  attributionWindowDays: 60,
  payoutCadence: "Monthly",
  minimumPayoutUsd: 50,
  clawbackWindowDays: 60,
  demoAccountCount: 1,
  effectiveDate: "2026-02-01",
  initialTermMonths: 12,
  autoRenewal: true,
};

export const referrals: Referral[] = [
  {
    id: "ref_abc",
    customerName: "ABC Trucking",
    clickedAt: "Jan 8",
    signupStatus: "Paid",
    attributed: true,
    netMrr: 299,
    commissionStatus: "Eligible",
  },
  {
    id: "ref_desert",
    customerName: "Desert Linehaul",
    clickedAt: "Jan 12",
    signupStatus: "Signed Up",
    attributed: true,
    netMrr: 499,
    commissionStatus: "Eligible",
  },
  {
    id: "ref_valley",
    customerName: "Valley Freight",
    clickedAt: "Jan 16",
    signupStatus: "Trial Started",
    attributed: true,
    netMrr: 199,
    commissionStatus: "Clawback Window",
  },
  {
    id: "ref_sonoran",
    customerName: "Sonoran Produce Logistics",
    clickedAt: "Jan 20",
    signupStatus: "Clicked",
    attributed: true,
    netMrr: 0,
    commissionStatus: "Pending",
  },
];

export const payouts: Payout[] = [
  {
    id: "po_feb",
    period: "February 2026",
    grossReferralMrr: 2285,
    earnings: 342.75,
    adjustments: -50,
    finalPayout: 292.75,
    status: "Scheduled",
    payoutDate: "Feb 15",
  },
  {
    id: "po_jan",
    period: "January 2026",
    grossReferralMrr: 8270,
    earnings: 1240.5,
    adjustments: 0,
    finalPayout: 1240.5,
    status: "Paid",
    payoutDate: "Jan 15",
  },
];

export const adminPartners = [
  {
    ...acmePartner,
    lifecycleStage: "active" as const,
    stageLabel: "Active",
    contractStatus: "Signed",
    payoutStatus: "Ready",
    demoStatus: "Active",
    referrals: 8,
    mrr: 2285,
    pendingEarnings: 342.75,
    paidEarnings: 1240.5,
    nextAction: "Monitor",
    stuckReason: "",
  },
  {
    id: "partner_desert_insurance",
    legalName: "Desert Insurance Group LLC",
    displayName: "Desert Insurance Group",
    type: "Insurance broker",
    tier: "Silver" as const,
    ownerName: "Mihir",
    primaryContactName: "Lena Ortiz",
    primaryContactEmail: "lena@desertinsurance.example",
    signingAuthorityName: "Gabe North",
    signingAuthorityEmail: "gabe@desertinsurance.example",
    lifecycleStage: "stuck" as const,
    stageLabel: "Stuck",
    contractStatus: "Signed",
    payoutStatus: "Incomplete",
    demoStatus: "Locked",
    referrals: 0,
    mrr: 0,
    pendingEarnings: 0,
    paidEarnings: 0,
    nextAction: "Send payout reminder",
    stuckReason: "Signed but no payout setup for 5 days",
  },
  {
    id: "partner_fleetfuel",
    legalName: "FleetFuel Advisors Inc.",
    displayName: "FleetFuel Advisors",
    type: "Fuel consultant",
    tier: "Gold" as const,
    ownerName: "Mihir",
    primaryContactName: "Priya Shah",
    primaryContactEmail: "priya@fleetfuel.example",
    signingAuthorityName: "Priya Shah",
    signingAuthorityEmail: "priya@fleetfuel.example",
    lifecycleStage: "stuck" as const,
    stageLabel: "Activation risk",
    contractStatus: "Countersigned",
    payoutStatus: "Ready",
    demoStatus: "Active",
    referrals: 0,
    mrr: 0,
    pendingEarnings: 0,
    paidEarnings: 0,
    nextAction: "Schedule activation call",
    stuckReason: "Active but no referrals after 30 days",
  },
  {
    id: "partner_routewise",
    legalName: "RouteWise Consulting LLC",
    displayName: "RouteWise Consulting",
    type: "Dispatch-as-a-service",
    tier: "Silver" as const,
    ownerName: "Mihir",
    primaryContactName: "Noah Reed",
    primaryContactEmail: "noah@routewise.example",
    signingAuthorityName: "Dana Kim",
    signingAuthorityEmail: "dana@routewise.example",
    lifecycleStage: "contract_sent" as const,
    stageLabel: "Contract pending",
    contractStatus: "Sent",
    payoutStatus: "Not started",
    demoStatus: "Locked",
    referrals: 0,
    mrr: 0,
    pendingEarnings: 0,
    paidEarnings: 0,
    nextAction: "Resend contract reminder",
    stuckReason: "Contract pending signature",
  },
];

export const lifecycleEvents = [
  { label: "Terms saved", owner: "Mihir", status: "Complete", date: "Jan 22" },
  { label: "DocuSign envelope sent", owner: "Marcus Reyes", status: "Complete", date: "Jan 23" },
  { label: "Contract countersigned", owner: "Legal", status: "Complete", date: "Jan 24" },
  { label: "Stripe Connect ready", owner: "Sarah Mendez", status: "Complete", date: "Jan 25" },
  { label: "NavPro demo account active", owner: "NavPro Engineering", status: "Complete", date: "Jan 25" },
  { label: "Referral link issued", owner: "Portal", status: "Complete", date: "Jan 26" },
  { label: "February payout scheduled", owner: "Finance", status: "In review", date: "Feb 10" },
];

export const referralCode = "ACME-FUEL-15";
export const referralLink = "https://truckbuyer.com/navpro?ref=ACME-FUEL-15";
